# main items router
twitterator_test:
    path:     /test
    defaults: { _controller: TwitteratorBundle:Tweets:index }
    condition: "context.getMethod() in ['POST', 'GET', 'HEAD', 'OPTIONS']"

twitterator_list:
    path:     /
    defaults: { _controller: TwitteratorBundle:Tweets:usersList }
    condition: "context.getMethod() in ['GET', 'HEAD', 'OPTIONS']"

twitterator_search:
    path:     /search
    defaults: { _controller: TwitteratorBundle:Tweets:search }
    condition: "context.getMethod() in ['POST', 'GET', 'HEAD', 'OPTIONS']"

twitterator_profile:
    path:     /{screen_name}
    defaults: { _controller: TwitteratorBundle:Tweets:userProfile }
    condition: "context.getMethod() in ['GET', 'HEAD', 'OPTIONS']"
